SET SERVEROUTPUT on;

DECLARE
    TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
    EMPLS EMPLEADOS;
  BEGIN
       SELECT * BULK COLLECT INTO EMPLS FROM EMPLOYEES WHERE SALARY > 5000;

       FOR I in 1..EMPLS.count loop
          DBMS_OUTPUT.PUT_LINE(EMPLS(i).FIRST_NAME) ;
       end loop;
END;